version: '3'

services:
  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_DB: classifieds_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 777
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql